# 1. Allocate GPU command:

* Meeting with Daisy and Ella to work on allocating the GPU.
* The command:
```
torch.cuda.set_device(2) 
print("Running on GPU: " + str(torch.cuda.current_device()))
```

* The 3rd GPU is being used:
<img width="829" alt="Screenshot 2023-07-25 at 6 59 25 PM" src="https://github.com/chauvuha/ARCS_Lab_Reports/assets/79251745/238de3a8-d924-4960-8068-2062f064ac1c">
<img width="629" alt="Screenshot 2023-07-25 at 7 11 49 PM" src="https://github.com/chauvuha/ARCS_Lab_Reports/assets/79251745/bcd85044-1472-482c-abb8-25895c26b354">

* The errors:
  * PosixPath
<img width="915" alt="Screenshot 2023-07-26 at 12 20 07 AM" src="https://github.com/chauvuha/ARCS_Lab_Reports/assets/79251745/fae023f0-ec06-4836-b960-9af56c0ba695">
  * Fixed it by putting str in front:

```
           # Getting the current image's label
        label_name = filename_to_class(str(img_filename))
        label = self.class_indices[label_name]
        
        # Getting the previous image's label
        # The default is 'forward'
        cmd_name = 'forward'
        
        # If the index is not 0, the cmd is determined by the previous img_filename
        if index != 0:
            prev_img_filename = self.all_filenames[index-1]
            cmd_name = filename_to_class(str(prev_img_filename))            
        cmd = self.class_indices[cmd_name]
```
* Compared resnet18 and resnet34:

* Commands that I used:
  * python CmdImageClassification-test-largedataset resnet34 'data' --pretrained
* The models are saved after training:
<img width="1143" alt="Screenshot 2023-07-26 at 12 18 14 AM" src="https://github.com/chauvuha/ARCS_Lab_Reports/assets/79251745/c7b5de4e-e256-4213-8c1a-fccecbe3c471">

# Issues:

* When Francisco tried to download our model and put inside the inference.py file, we are getting this error:
(unreal) PS C:\Users\alnj2022\Documents\VisualStudioCode\OldenborgTraining> python inference.py C:\Users\alnj2022\Downloads\classification-resnet34-pretrained-1.pth UE_Screenshots
Traceback (most recent call last):
  File "C:\Users\alnj2022\Documents\VisualStudioCode\OldenborgTraining\inference.py", line 95, in <module>
    main()
  File "C:\Users\alnj2022\Documents\VisualStudioCode\OldenborgTraining\inference.py", line 55, in main
    learn = load_learner(args.model)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alnj2022\.conda\envs\unreal\Lib\site-packages\fastai\learner.py", line 451, in load_learner
    res.dls.cpu()
    ^^^^^^^
AttributeError: 'collections.OrderedDict' object has no attribute 'dls'

* Possible solutions:
  * export the model before learner.load() with this command: learn.export(model.pkl)

* Added img_size and valid_pct as arguments to the training script. 


# Plans:
* Look into Blender
* Figure out how to compare loss, epoch across different runs in wandb
* Add parse.args
